name: Build Vanilla

on:
  push:
    tags:
      - vanilla-*

jobs:
  build-vanilla:
    name: build vanilla
    runs-on: self-hosted
    # runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Get Version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./vanilla
          file: vanilla/Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v7,linux/arm64,linux/ppc64le
          push: true
          tags: |
            crnlabs/terraria:vanilla-latest
            crnlabs/terraria:${{ steps.get_version.outputs.VERSION }}
